services:
  apisix-test-runner:
    container_name: apisix-custom-test-runner
    image: apache/apisix:custom
    restart: no
    volumes:
      - ./conf/config.yaml:/home/apisix/apisix_src/conf/config.yaml
      - ../../apisix/plugins:/home/apisix/apisix_src/apisix/plugins
      - ../../t:/home/apisix/apisix_src/t/custom
    ports:
      - "9080:9080/tcp"
      - "9443:9443/tcp"
    command:
      - /home/apisix/run_tests.sh
      - "-f"
      - "-t"
      - "/home/apisix/apisix_src/t/custom/demo/demo.t"
